### ISSUE TITLE
Missing cut in repeat loop

### ISSUE THREAD

**Issue by pmoura** [friguzzi/aleph#12]
The repeat loop in the following clause is missing a cut (found by the Logtalk linter):

https://github.com/friguzzi/aleph/blob/26eef74e954d62d198190403c095a4d4765bd9d7/prolog/aleph.pl#L11272-L11278

Backtracking to a call to `show_file/1` will result in a runtime error (trying to read from a closed stream). Tp prevent this from happening, you can rewrite the clause as:

```logtalk
show_file(File):- 
    aleph_open(File,read,Stream),  
    repeat, 
    read(Stream,Clause), 
    (   Clause = end_of_file -> close(Stream), !
    ;   writeq(Clause), write('.'), nl, fail
    ).
```

**Comment by friguzzi** [comment]
Thanks, fixed in https://github.com/friguzzi/aleph/commit/26eef74e954d62d198190403c095a4d4765bd9d7

**Comment by friguzzi** [comment]
Sorry, it's fixed in https://github.com/friguzzi/aleph/commit/4ae3dd8a9a8d4693a77ad20c97c5989918a2fd20
