### ISSUE TITLE
Having problem with test_pos setting

### ISSUE THREAD

**Issue by harshakokel** [friguzzi/aleph#14]
Hello,

I am getting the following errors while setting the test_pos parameter. Any idea what am I doing wrong?

Trial 1:
`:- aleph_set(test_pos,test_file_pos).` 
Error:
```
[error] [set(test_pos,test_file_pos)]
```

Trial 2:
`:- aleph_set(test_pos,'./test_file_pos.f').`

Error
```
Warning: Unknown procedure: aleph:test_file/2
Warning:   However, there are definitions for:
Warning:         aleph:test_file/3
Warning:         aleph:test_files/3
```

**Comment by friguzzi** [comment]
Thanks for reporting and for the pull request, I merged it.
