### ISSUE TITLE
Loads of output even when verbose is 0

### ISSUE THREAD

**Issue by JeanChristopheRohner** [friguzzi/aleph#16]
Hi!
Not sure if this is a bug or not but i get several hundreds (if not thousands) of lines of output even with
`:-aleph_set(verbose, 0).`.
Thanks!
/JCR

**Comment by friguzzi** [comment]
Hi,
this is a feature of the original code of Aleph, if you look at the source code you will find that the verbosity is rarely checked.
I just ported Aswhin Srinivasan's code to SWIPL, I suggest you contact him to highlight this problem.

Best
Fabrizio

**Comment by JeanChristopheRohner** [comment]
Thanks, i'll have a look at the source.
Kind regards, JCR
