### ISSUE TITLE
Reading lists dynamically

### ISSUE THREAD

**Issue by durgeshnandini** [friguzzi/aleph#18]
I am fairly new to Prolog and Aleph and need help with the following.

There are two lists: list_A and list_B, where list_A is a shorter list than list_B. For each item in list_A I want to check whether it is present in list_B. I have the following code for the same:

> common_list([X],[X]).
> common_list([X|Tail],Y):- member(X,Y).
> common_list([X|Tail],Y):- common_list(Tail,Y).

But the problem is that I want to input list_A dynamically and want to define the elements of list_B from a database. For the output, I then want to list the elements that matched as a result.

So, for example,
- list_B = [cho,pip,lib,exo,ram,lik,mangoes]
- then I want that my program inputs a list from a sentence, say the sentence is 'I like mangoes' then the list should read list_A = [like,mangoes]
- and then the output should be: true; mangoes.

So my main questions are:
- how can I take the list_A dynamically as input?
- how can I read list_B from a database?
- how do I print the matching list elements?

**Comment by friguzzi** [comment]
This is not the right place to ask this question, as it is not related to Aleph. You should ask it to the SWI-Prolog forum https://swi-prolog.discourse.group/

**Comment by durgeshnandini** [comment]
Hello,
Thank you for your response.
I have posted at multiple places, but unfortunately, I have no answer. Can you please provide any hints?
Also, can you please suggest other communities apart from the SWI-Prolog forum?
    On Sunday, 10 April, 2022, 10:36:19 am GMT+2, Fabrizio Riguzzi ***@***.***> wrote:  
 
 


Closed #18.

**Comment by friguzzi** [comment]
I haven't seen you post on the SWI-Prolog forum

**Comment by durgeshnandini** [comment]
Hello,
I reposted it today also, please have a look at https://swi-prolog.discourse.group/t/reading-list-dynamically-for-prolog-and-aleph/5254
    On Sunday, 10 April, 2022, 12:42:30 pm GMT+2, Fabrizio Riguzzi ***@***.***> wrote:  
 
 


I haven't seen you post on the SWI-Prolog forum
