### ISSUE TITLE
A potential bug about reset_succ

### ISSUE THREAD

**Issue by Zhang-Liao** [friguzzi/aleph#19]
Line 1137 of "aleph.pl" is `reset_succ,`. But the definition of `reset_succ` is `reset_succ(M):-`. It requires an argument. Sometimes it seems can cause warnings and even segmentation faults.
```
Warning: Unknown procedure: aleph:reset_succ/0
Warning:   However, there are definitions for:
Warning:         aleph:reset_succ/1
```

**Comment by friguzzi** [comment]
Thanks, fixed in 8808760e7dedd7d2ee95de87a931de2606020a16
