### ISSUE TITLE
May need some special treatment for the evaluation function 'accuracy'

### ISSUE THREAD

**Issue by Zhang-Liao** [friguzzi/aleph#20]
The definition is 
```
evalfn(accuracy,[P,N|_],Val):-
	(P = -inf -> Val is 0.5;
		Val is P / (P + N)), !.
```
It causes an error when P + N = 0. It may happen when users disable the bottom clause and define their own refinement operators. It is possible that generating a clause that does not satisfy any examples.

Perhaps return accuracy 0 when P + N = 0?

**Comment by friguzzi** [comment]
I made it return 0.5 as for the other default case.
Fixed in 90b7837709f3753c6b8a384101844f56c8438c5a
